### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by LukasKretschmann** [irjensen/mandelbrot-zoomer#1]
I got this error:

ipykernel_launcher.py: error: unrecognized arguments: -f C:\Users\Lukas\AppData\Roaming\jupyter\runtime\kernel-735764d3-4533-41ef-a225-1c5441499f99.json

Whats the probelm?

**Comment by irjensen** [comment]
It looks like you are trying to run the script in a Jupyter Notebook, but it is intended to be run directly from the terminal/command line. You could either run the script directly in the terminal/command line with `python3 path/to/zoom.py` or you may be able to run it in a notebook cell with `!python3 path/to/zoom.py`

If you are still having issues please provide more details about the environment you are using.
